---
title: "A running list of useful Bioinformatics definitions"
author: "Yang Zhang"
date: '2022-02-28'
categories: []
tags: []
subtitle: ''
slug: a-running-list-of-useful-bioinformatics-definitions
---

Here is a list of useful definitions for Bioinformatics, it mainly
serves as a reference for myself but hopefully it will be useful for
other folks as well.

-   Pearson vs Kendall vs Spearman 
    + Pearson 
        $r=\frac{\sum(X-\bar{X})(Y-\bar{Y})}{\sqrt{\sum(X-\bar{X})^2\sum(Y-\bar{Y})^2}}$
    + Kendall
        $\tau=\frac{n_c-n_d}{n_c+n_d}=\frac{n_c-n_d}{n(n-1)/2}$
        where $n_c$ is number of concordant pairs and $n_d$ is number of discordant pairs
    + Spearman
        $\rho=\frac{\sum_{i=1}^{n}(R(x_i)-\bar{R(x)})(R(y_i)-\bar{R(y)})}{\sqrt{\sum_{i=1}^{n}(R(x_i)-\bar{R(x)})^2\sum_{i=1}^{n}(R(y_i)-\bar{R(y)})^2}}$
        where $R(x_i)$ is rank of $x_i$ and $R(y_i)$ is rank of $y_i$

- PCA vs PCOA vs OPLS-DA 
  + PCA is based on Euclidean distance, it is unsupervised and works well when inter-group difference is big and intra-group has relatively small difference.
  + PCOA is similar to PCA but based on non-Euclidean distance.
  + PLS is supervised, O stands for orthogonal and works well when sample size is small relative to feature numbers.
  
- ANOVA: Analysis of Variance

- ANOSIM: ANalysis Of Similarities

- Prokka: rapid prokaryotic genome annotation